# ======================================= #
#                                         #
#                M O D E S                #
#                                         #
# ======================================= #

- alias: Study
  trigger:
    - platform: state
      entity_id: input_boolean.study_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'on'
  action:
    - scene: scene.study
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.game_mode
  mode: single

- alias: Mood
  trigger:
    - platform: state
      entity_id: input_boolean.study_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'on'
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
  action:
    - scene: scene.scene_mood
  mode: single

- alias: Game
  trigger:
    - platform: state
      entity_id: input_boolean.game_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'on'
  action:
    - scene: scene.game
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.study_mode
        - input_boolean.sleep_mode
  mode: single

- alias: Sleep
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: 'on'
  action:
    - scene: scene.scene_sleep
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.study_mode
        - input_boolean.game_mode
  mode: single

- alias: Shutdown input_booleans
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id:
            - scene.shut_down
        domain: scene
        service: turn_on
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.game_mode
        - input_boolean.study_mode
  mode: single

  # ======================================= #
  #                                         #
  #             P R E S E N S E             #
  #                                         #
  # ======================================= #

- alias: Away
  trigger:
    - platform: state
      entity_id: sensor.presence
      from: 'home'
      to: 'not_home'
      for: "00:05:00"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_mode
    - service: scene.scene_shut_modes_down
  mode: single

- alias: Return Home
  trigger:
    - platform: state
      entity_id: sensor.presence
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.home_mode
        - input_boolean.study_mode
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest
  mode: single

  # ======================================= #
  #                                         #
  #                S L E E P                #
  #                                         #
  # ======================================= #

- alias: Go to Sleep
  trigger:
    - platform: state
      entity_id: binary_sensor.pressure_pillow_contact
      to: 'off' # pressed
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
  mode: single

- alias: Wake Up
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: 'on' # released
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - condition: state
      entity_id: binary_sensor.pressure_pillow_contact
      state: 'on'
    - "{{ states('sensor.time') >= (states.input_datetime.morning.attributes.timestamp | int) | timestamp_custom('%H:%M', False) }}"
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.study_mode
        - input_boolean.morning_check
  mode: single

- alias: Morning Routine
  description: Gradually turn on Lights & open Curtain before Wake
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (((states.input_datetime.morning.attributes.timestamp | int ) - 20*60) | timestamp_custom('%H:%M', False)) }}"
      # 30 minutes (1 min = 60 sec)
  condition:
    - condition: state
      entity_id: input_boolean.morning_check
      state: 'off'
  action:
    - service: script.morning_routine
  mode: single

- alias: Reset Day
  initial_state: true
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: input_number.reload
      entity_id: input_number.morning_current_state
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_check

  # ======================================= #
  #                                         #
  #               L O A D E R               #
  #                                         #
  # ======================================= #

- alias: Turn Off Loading Wheel
  initial_state: true
  trigger:
    - platform: state
      entity_id: ['switch.curtain', 'switch.desktop']
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: >
          {{ trigger.entity_id | replace(trigger.entity_id.split('.')[0], 'input_boolean') }}

- alias: Turn Off Loading Wheel-failsafe
  initial_state: true
  trigger:
    - platform: state
      entity_id: ['input_boolean.curtain', 'input_boolean.desktop']
      to: 'on'
      for:
        minutes: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: >
          {{ trigger.entity_id }}

  # ======================================= #
  #                                         #
  #                  E T C                  #
  #                                         #
  # ======================================= #

- alias: Close Curtain After Noon
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.curtain
        position: 0
