# ======================================= #
#                                         #
#                M O D E S                #
#                                         #
# ======================================= #

- alias: Study
  trigger:
    - platform: state
      entity_id: input_boolean.study_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - scene: scene.study
    - scene: scene.scene_stand_study
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.media_mode
        - input_boolean.hip_mode
        - input_boolean.cozy_mode
  mode: single

- alias: Media
  trigger:
    - platform: state
      entity_id: input_boolean.media_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - scene: scene.scene_media
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.study_mode
        - input_boolean.sleep_mode
        - input_boolean.hip_mode
        - input_boolean.cozy_mode
  mode: single

- alias: Sleep
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - scene: scene.scene_sleep
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.study_mode
        - input_boolean.media_mode
        - input_boolean.hip_mode
        - input_boolean.cozy_mode
  mode: single

- alias: Cozy
  trigger:
    - platform: state
      entity_id: input_boolean.cozy_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - scene: scene.scene_stand_cozy
    - scene: scene.scene_cozy_mode
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.study_mode
        - input_boolean.hip_mode
        - input_boolean.media_mode
  mode: single

- alias: Hip
  trigger:
    - platform: state
      entity_id: input_boolean.hip_mode
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - scene: scene.scene_hip_mode
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.study_mode
        - input_boolean.cozy_mode
        - input_boolean.media_mode
  mode: single

- alias: Shutdown input_booleans
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id:
            - scene.shut_down
        domain: scene
        service: turn_on
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.media_mode
        - input_boolean.study_mode
        - input_boolean.cozy_mode
        - input_boolean.hip_mode
  mode: single

  # ======================================= #
  #                                         #
  #             P R E S E N S E             #
  #                                         #
  # ======================================= #

- alias: Away
  trigger:
    - platform: state
      entity_id: sensor.presence
      from: 'home'
      to: 'not_home'
      for: "00:05:00"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_mode
    - service: scene.scene_shut_modes_down
  mode: single

- alias: Return Home
  trigger:
    - platform: state
      entity_id: sensor.presence
      from: 'not_home'
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: 
        - input_boolean.home_mode
        - input_boolean.study_mode
  mode: single

  # ======================================= #
  #                                         #
  #                S L E E P                #
  #                                         #
  # ======================================= #

- alias: Go to Sleep
  trigger:
    - platform: state
      entity_id: binary_sensor.pressure_pillow_contact
      to: 'off' # pressed
      for: "00:00:03"
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.sleep_mode
  mode: single

- alias: Wake Up
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: 'on' # released
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'on'
    - condition: state
      entity_id: binary_sensor.pressure_pillow_contact
      state: 'on'
  action:
    - choose:
      - conditions: 
        - "{{ states('sensor.time') >= (states.input_datetime.morning.attributes.timestamp | int) | timestamp_custom('%H:%M', False) }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id:
                - input_boolean.study_mode
                - input_boolean.morning_check
      - conditions:
        - "{{ states('sensor.time') < (states.input_datetime.morning.attributes.timestamp | int) | timestamp_custom('%H:%M', False) }}"
        sequence:
          - service: light.turn_on
            data:
              brightness: 180
              color_temp: 500
            target:
              entity_id: light.under_desk_strip_light
  mode: single

- alias: Morning Routine
  description: Gradually turn on Lights & open Curtain before Wake
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (((states.input_datetime.morning.attributes.timestamp | int ) - 20*60) | timestamp_custom('%H:%M', False)) }}"
      # 20 minutes (1 min = 60 sec)
  condition:
    - condition: state
      entity_id: input_boolean.morning_check
      state: 'off'
    - condition: state
      entity_id: input_boolean.home_mode
      state: 'on'
  action:
    - service: script.morning_routine
  mode: single

- alias: Reset Day
  initial_state: true
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: input_number.reload
      entity_id: input_number.morning_current_state
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_check
  mode: single

  # ======================================= #
  #                                         #
  #               L O A D E R               #
  #                                         #
  # ======================================= #

- alias: Turn Off Loading Wheel
  initial_state: true
  trigger:
    - platform: state
      entity_id: ['switch.curtain', 'switch.desktop']
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: >
          {{ trigger.entity_id | replace(trigger.entity_id.split('.')[0], 'input_boolean') }}
  mode: single

- alias: Turn Off Loading Wheel-failsafe
  initial_state: true
  trigger:
    - platform: state
      entity_id: ['input_boolean.curtain', 'input_boolean.desktop']
      to: 'on'
      for:
        minutes: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: >
          {{ trigger.entity_id }}
  mode: single