# ======================================= #
#                                         #
#                M O D E S                #
#                                         #
# ======================================= #

- id: "1600589105104"
  alias: Study
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.study_mode
      from: "off"
      to: "on"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: "on"
  action:
    - scene: scene.study
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.game_mode
  mode: single

- id: "1600589225737"
  alias: Game
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.game_mode
      from: "off"
      to: "on"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: "on"
  action:
    - scene: scene.game
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.study_mode
        - input_boolean.sleep_mode
  mode: single

- id: "1600590060785"
  alias: Sleep
  description: ""
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      from: "off"
      to: "on"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: "on"
  action:
    - scene: scene.scene_sleep
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.study_mode
        - input_boolean.game_mode
  mode: single

- id: "1600599118233"
  alias: Shutdown input_booleans
  description: ""
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        service_data:
          entity_id:
            - scene.shut_down
        domain: scene
        service: turn_on
  condition: []
  action:
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.sleep_mode
        - input_boolean.game_mode
        - input_boolean.study_mode
  mode: single

  # ======================================= #
  #                                         #
  #             P R E S E N S E             #
  #                                         #
  # ======================================= #

- id: "1600591421096"
  alias: Away
  description: ""
  trigger:
    - platform: state
      entity_id: sensor.presence
      from: home
      to: not_home
      for: "00:05:00"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_mode
  mode: single

- id: "1609050516870"
  alias: Motion -> Home Mode
  description: Set Mode to Home when motion is detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: "on"
  condition:
    - condition: state
      entity_id: input_boolean.home_mode
      state: "off"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.home_mode
    - service: input_boolean.turn_on
      entity_id: input_boolean.study_mode
  mode: single

- id: "1609053497602"
  alias: Not Home -> Back to Away
  description: Back to Away Mode when you're not home
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: "off"
      for: 00:05:00
  condition:
    - condition: state
      entity_id: sensor.presence
      state: "not_home"
    - condition: state
      entity_id: input_boolean.home_mode
      state: "on"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.home_mode
    - service: scene.turn_on
      entity_id:
        - scene.shut_down
        - scene.scene_shut_modes_down
  mode: single

  # ======================================= #
  #                                         #
  #                S L E E P                #
  #                                         #
  # ======================================= #

- id: "1610451459913"
  alias: Go to Sleep
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.pressure_pillow_contact
      to: "off" # pressed
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: "on"
  action:
    - service: input_boolean.turn_on
      data: {}
      entity_id: input_boolean.sleep_mode
  mode: single

- id: "1610451842424"
  alias: Wake Up
  description: ""
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_occupancy
      to: "on"
  condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.home_mode
          state: "on"
        - condition: state
          entity_id: input_boolean.sleep_mode
          state: "on"
        - condition: state
          entity_id: binary_sensor.pressure_pillow_contact
          state: "on"
        - "{{ states('sensor.time') >= (states.input_datetime.morning.attributes.timestamp | int) | timestamp_custom('%H:%M', False) }}"
  action:
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.study_mode
        - input_boolean.morning_check
  mode: single

- alias: Morning Routine
  description: Gradually turn on Lights & open Curtain before Wake
  initial_state: true
  trigger:
    - platform: template
      value_template: "{{ states('sensor.time') == (((states.input_datetime.morning.attributes.timestamp | int ) - 20*60) | timestamp_custom('%H:%M', False)) }}"
      # 30 minutes (1 min = 60 sec)
  action:
    - service: script.morning_routine
  mode: single

- alias: Full Wake Up
  trigger:
    - platform: state
      entity_id: input_boolean.morning_check
      to: "on"
  action:
    - service: light.turn_on
      data:
        entity_id: group.light
        brightness: 255
    - service: cover.set_cover_position
      data:
        entity_id: cover.curtain
        position: 100

- alias: Reset Day
  initial_state: true
  trigger:
    - platform: time
      at: "00:00:00"
  action:
    - service: input_number.reload
      entity_id: input_number.morning_current_state
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_check

  # ======================================= #
  #                                         #
  #               L O A D E R               #
  #                                         #
  # ======================================= #

- alias: Turn Off Loading Wheel
  initial_state: true
  trigger:
    - platform: state
      entity_id: ["switch.curtain"]
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: >
          {{ trigger.entity_id | replace(trigger.entity_id.split('.')[0], 'input_boolean') }}

- alias: Turn Off Loading Wheel-failsafe
  initial_state: true
  trigger:
    - platform: state
      entity_id: ["input_boolean.curtain"]
      to: "on"
      for:
        minutes: 1
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: >
          {{ trigger.entity_id }}

  # ======================================= #
  #                                         #
  #                  E T C                  #
  #                                         #
  # ======================================= #

- alias: Close Curtain After Noon
  initial_state: true
  trigger:
    - platform: state
      entity_id: sun.sun
      to: below_horizon
  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.curtain
        position: 0
