base:
  aspect_ratio: 1/1
  show_state: true
  show_icon: false
  state:
    - value: 'on'
      styles:
        card: [background-color: 'rgba(255, 255, 255, 0.8)']
        name: [color: 'rgba(0, 0, 0, 0.7)']
        state: [color: 'rgba(0, 0, 0, 0.35)']
    - value: 'off'
      styles:
        name: [color: 'rgba(255, 255, 255, 0.3)']
        state: [color: 'rgba(255, 255, 255, 0.15)']
  tap_action:
    action: toggle
    haptic: light
  styles:
      name: [top: 60%, left: 8%, line-height: 2vw, position: absolute]
      state: [top: 78%, left: 8%, line-height: 2vw, position: absolute]
      card: [font-family: Sf Display, letter-spacing: 0.05vw, font-weight: 400, font-size: 1.3em, background-color: 'rgba(115, 115, 115, 0.2)', border-radius: 0.8vw, box-shadow: none, transition: none]

mode:
  template: base
  tap_action:
    action: call-service
    service: input_boolean.turn_on
    service_data:
      entity_id: '[[[ return entity.entity_id ]]]'

round_button:
  aspect_ratio: 1/1
  show_name: false
  show_state: false
  show_icon: false
  state:
    - value: 'on'
      styles:
        card: [background-color: 'rgba(255, 255, 255, 0.6)']
    - value: ''
  tap_action:
    action: toggle
    haptic: light
  styles:
    card: [font-family: Sf Display, letter-spacing: 0.05vw, font-weight: 400, font-size: 1.3em, background-color: 'rgba(255, 255, 255, 0.2)', border-radius: 10vw, box-shadow: none, transition: none]

sensor:
  template: base
  tap_action:
    action: none

loader:
  custom_fields:
    loader: >
      [[[ if (states[entity.entity_id.replace(entity.entity_id.split('.')[0], 'input_boolean')].state === 'on') { 
      return '<img src="/local/loader.svg" width="100%">'; } ]]]
  styles:
    custom_fields:
      loader:
        [filter: "[[[ return entity.state === 'off' ? 'invert(1)' : 'none'; ]]]", 
          top: 3%, left: 60%, width: 3.7vw, position: absolute, opacity: 0.6]

light_norgb:
  template: base
  hold_action:
    action: call-service
    service: browser_mod.popup
    service_data:
      title: '[[[ return entity.attributes.friendly_name ]]]'
      deviceID: this
      card:
        type: entities
        entities:
          - type: custom:light-popup-card
            entity: '[[[ return entity.entity_id ]]]'
            icon: none
            fullscreen: false
            brightnessWidth: 130px
            brightnessHeight: 360px
            borderRadius: 1.7em
            sliderColor: '#c7c7c7'
            sliderTrackColor: rgba(25, 25, 25, 0.9)
            actionSize: 4.5em
            actionsInARow: 2
            style: |
              #popup {
                margin: -2.4em 0 1.4em 0; }
              #popup > div.range-holder > input[type=range] {
                cursor: grab; }
              #brightnessValue {
                color: rgba(255, 255, 255, 0.8); margin: -1.9em 0 0 0; font-size: 2em; font-weight: 400; 
                position: absolute; z-index: 100; font-family: SF Display; letter-spacing: 0.02em; pointer-events: none; 
                mix-blend-mode: difference; text-align:center; width: 3.4em; height: 3.4em; }
              #popup > div.range-holder > input[type=range]::-webkit-slider-thumb {
                border: 0; eight: 0; width: 0; cursor: grabbing; }
              #popup > div.action-holder > div > div {
                margin: 0.8em 0.5em -0.8em 0.5em; }
              #popup > div.action-holder > div:last-child > div:last-child > .color {
                background: radial-gradient(circle, rgba(255,255,255,1) 0%, rgba(255,255,255,0) 80%), 
                conic-gradient(rgb(120,39,230), rgb(230,34,231), rgb(228,5,136), rgb(228,25,25), rgb(229,105,30), rgb(232,226,46), 
                rgb(125,230,41), rgb(52,232,40), rgb(51,231,92), rgb(52,232,224),rgb(32,125,229), rgb(18,39,229), rgb(120,39,230));
                border-width: 2px; border-color: #e6e6e6; --size: 4.4em !important; }

light:
  template: base
  hold_action:
    action: call-service
    service: browser_mod.popup
    service_data:
      title: '[[[ return entity.attributes.friendly_name ]]]'
      deviceID: this
      card:
        type: entities
        entities:
          - type: custom:light-popup-card
            entity: '[[[ return entity.entity_id ]]]'
            icon: none
            fullscreen: false
            brightnessWidth: 130px
            brightnessHeight: 360px
            borderRadius: 1.7em
            sliderColor: '#c7c7c7'
            sliderTrackColor: rgba(25, 25, 25, 0.9)
            actionSize: 4.5em
            actionsInARow: 2
            style: |
              #popup {
                margin: -2.4em 0 1.4em 0; }
              #popup > div.range-holder > input[type=range] {
                cursor: grab; }
              #brightnessValue {
                color: rgba(255, 255, 255, 0.8); margin: -1.9em 0 0 0; font-size: 2em; font-weight: 400; 
                position: absolute; z-index: 100; font-family: SF Display; letter-spacing: 0.02em; pointer-events: none; 
                mix-blend-mode: difference; text-align:center; width: 3.4em; height: 3.4em; }
              #popup > div.range-holder > input[type=range]::-webkit-slider-thumb {
                border: 0; eight: 0; width: 0; cursor: grabbing; }
              #popup > div.action-holder > div > div {
                margin: 0.8em 0.5em -0.8em 0.5em; }
              #popup > div.action-holder > div:last-child > div:last-child > .color {
                background: radial-gradient(circle, rgba(255,255,255,1) 0%, rgba(255,255,255,0) 80%), 
                conic-gradient(rgb(120,39,230), rgb(230,34,231), rgb(228,5,136), rgb(228,25,25), rgb(229,105,30), rgb(232,226,46), 
                rgb(125,230,41), rgb(52,232,40), rgb(51,231,92), rgb(52,232,224),rgb(32,125,229), rgb(18,39,229), rgb(120,39,230));
                border-width: 2px; border-color: #e6e6e6; --size: 4.4em !important; }
            actions:
              - service: light.turn_on
                service_data:
                  entity_id: '[[[ return entity.entity_id ]]]'
                  color_temp: 153
                color: "#d8d9e1"
              - service: light.turn_on
                service_data:
                  entity_id: '[[[ return entity.entity_id ]]]'
                  color_temp: 326
                color: "#d5b08d"
              - service: light.turn_on
                service_data:
                  entity_id: '[[[ return entity.entity_id ]]]'
                  color_temp: 500
                color: "#ce944b"
              - service: browser_mod.popup
                service_data:
                  title: '[[[ return entity.attributes.friendly_name ]]]'
                  deviceID: this
                  card:
                    type: entities
                    show_header_toggle: false
                    entities:
                      - entity: '[[[ return entity.entity_id ]]]'
                        secondary_info: last-changed
                      - type: custom:light-entity-card
                        entity: '[[[ return entity.entity_id ]]]'
                        brightness: false
                        color_temp: true
                        full_width_sliders: true
                        hide_header: true
                        show_slider_percent: true
                        smooth_color_wheel: true
                        consolidate_entities: true

icon_action:
  color: '#9da9a2'
  styles:
    card:
      [background: '#FFFFFF10', border-radius: 0.6em, box-shadow: none,
      transition: none, width: 4em, height: 3.7em]

name_action:
    styles:
      name:
        [display: flex, align-items: center, justify-content: center, margin-top: 0.5px]
      card:
        [background: '#FFFFFF10', color: '#262b2c', border-radius: 0.6em, box-shadow: none, 
        transition: none, width: 100%, padding: 1em 1.4em 1em 1.2em, font-size: 1.06em, 
        font-weight: 500, letter-spacing: 0.015em]
    style: '#name > ha-icon {width: 1.4em; margin-right: 0.3em; }'