# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml

frontend:
  themes: !include themes.yaml

# Text to speech
tts:
  - platform: naver_premium
    client_id: i85h2upfma
    client_secret: bSBGqyLPuva1FEHh6x1ojJZnhCq9E4VIwN9RHqjU
    emotion: 2

media_player:
  - platform: cast
  
# Cloud
cloud:

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include booleans.yaml
automation: !include automations.yaml

discovery:
  ignore:
    - yeelight
yeelight:
  devices:
    192.168.0.6:
      name: Xiaomi Desk Strip
      save_on_change: true
      
device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.0.41
    home_interval: 3
      
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

  - platform: steam_online
    api_key: 86AF8DF0E151A052F49E134A5477BE84
    accounts:
      - '76561198086996983'
      - '76561198086267709'
      - '76561198074838957'

  - platform: uptime
    name: Hassio uptime

  - platform: version
    source: hassio

  - platform: dnsip

  - platform: naver_weather
    name: Weather
    area: 'weather'
    
yahoofinance:
  symbols:
    - NVDA
    - TSLA
    - AAPL
    - CCIV
    - VLDR
    - IPOE

weather:
  - platform: naver_weather
    area: 'weather'
    sensor_use: 'Y'

browser_mod:

kakao_talk:
  api_key: 92f42c4d59a603cdd26c1bf1e3cb61c0
  redirect_uri: http://ha.stansign.duckdns.org
  send_to_friends: True
  
notify:
  - name: kakaotalk_noti
    platform: kakao_talk

logger:
  default: warn
  logs:
    custom_components.kakaotalk: debug
    custom_components.kakao_talk: debug