# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  allowlist_external_dirs:
    - '/config'
  customize: !include customize.yaml

lovelace:
  mode: yaml
  resources:
    [ {url: /hacsfiles/button-card/button-card.js,                                          type: module},
      {url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js,                           type: module},
      {url: /hacsfiles/lovelace-card-mod/card-mod.js,                                       type: module},
      {url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js,                    type: module},
      {url: /hacsfiles/rgb-light-card/card.js,                                              type: module},
      {url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,                     type: module},
      {url: /hacsfiles/lovelace-layout-card/layout-card.js,                                 type: module},
      {url: /hacsfiles/lovelace-gap-card/gap-card.js,                                       type: module},
      {url: /hacsfiles/mini-media-player/mini-media-player-bundle.js,                       type: module},
      {url: /hacsfiles/battery-state-card/battery-state-card.js,                            type: module},
      {url: /hacsfiles/lovelace-hui-element/hui-element.js,                                 type: module},
      {url: /hacsfiles/light-popup-card/light-popup-card.js,                                type: module},
      {url: /hacsfiles/light-entity-card/light-entity-card.js,                              type: module},
      {url: /hacsfiles/circle-sensor-card/circle-sensor-card.js,                            type: module},
      {url: /hacsfiles/bar-card/bar-card.js,                                                type: module},
      {url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js,                   type: module},
      {url: /hacsfiles/swipe-card/swipe-card.js,                                            type: module},
      {url: /hacsfiles/spotify-card/spotify-card.js,                                        type: module},
      {url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js,                       type: module} ]

logger:
  default: warn
  logs:
    homeassistant.components.rest_command: debug

frontend:
  themes: !include themes.yaml

# Cloud
cloud:

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
automation: !include automations.yaml
binary_sensor: !include binary_sensors.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml
rest_command: !include rest_command.yaml

discovery:
  ignore:
    - yeelight

tts:
  - platform: google_translate
    cache: true
    cache_dir: /tts
    service_name: google_say

yeelight:
  devices:
    192.168.0.6:
      name: Xiaomi Desk Strip
      save_on_change: true
      
device_tracker:
  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      hostname1: !secret iphone_detect

weather:
  - platform: naver_weather
    area: '경기도+부천시+상동+날씨'
    sensor_use: 'Y'

browser_mod:

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

spotcast:
  sp_dc: !secret spotcast_dc
  sp_key: !secret spotcast_key

wake_on_lan:

webostv:
  host: !secret livingroom_tv_ip
  name: Living Room TV

